color0 #000000
color1 #ff7092
color10 #20f6bb
color11 #fff687
color12 #1bcbfc
color13 #e5adfd
color14 #99d6fc
color15 #feffff
color2 #00faac
color3 #fef96a
color4 #00beff
color5 #de95ff
color6 #85cbfd
color7 #ffffff
color8 #000000
color9 #ff89a3
background #322957
cursor #20f6bb
cursor_text_color #feffff
foreground #e5e5e5
url_color #005bbb
selection_foreground #000000
selection_background #c1ddff
